title: cmb-journal-club
description: Computational Molecular Biology Journal Club
theme: just-the-docs

url: https://yelilab.github.io/cmb-journal-club

aux_links:
  Template Repository: https://github.com/yelilab/cmb-journal-club
